version: "3.8"

services:
  client:
    build: "./client"
    command: ./run_client.sh
    environment:
      - DEV_MODE=false
      - NODE_ENV=production
    volumes:
      - .:/code
      - /code/client/node_modules
    ports:
      - "8080:8080"
