---
# ---------------------------
# Test secret to get this running
# before deconstructing it
# ---------------------------
apiVersion: v1
kind: Secret
metadata:
  name: dpcreator-app-secrets
type: Opaque
stringData:
  secret-key: "SECRET_KEY!-ADD-REAL-KEY-HERE!--ADD-REAL-KEY!1234!"
  cryptography-key: "CRYPTOGRAPHY_KEY!-ADD-REAL-KEY!1234!"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpcreator-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpcreator
      tier: app
  template:
    metadata:
      labels:
        app: dpcreator
        tier: app
    spec:
      #restartPolicy: Always
      volumes:
        - name: dpcreator-volume
          emptyDir: {}
          # azureDisk:
          #  kind: Managed
          #  diskName: storage-dpcreator-files
          #  diskURI:
      containers:
        # -------------------------------------------------
        # (1) Nginx frontend: Separate requests to static files vs. Django app
        # -------------------------------------------------
        - name: dpcreator-nginx
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
              name: http
              protocol: TCP
          volumeMounts:
            # ----------------------------------
            # shared between containers
            # ----------------------------------
            - name: dpcreator-volume
              mountPath: /dpcreator_volume
              #subPath: 2ravens_org-apricot
              #readOnly: true
          #envFrom:
          #  - configMapRef:
          #      name: ravens-django-config-apricot
        # -------------------------------------------------
        # (2) Core application: Django + bundled static files
        # -------------------------------------------------
        - name: dpcreator-app
          image: {{ dpcreator_app_container }}:{{ dpcreator_container_tag }}
          imagePullPolicy: Always
          # TODO: update to gunicorn or similar
          command: [ "/bin/sh" ]
          args: [ "-c", "./migrate.sh && daphne -b 0.0.0.0 -p 8000 opendp_project.asgi_azure:application"]
          # args: [ "-c", "./migrate.sh && python manage.py runserver 0.0.0.0:8000"]
          ports:
            - name: dpcreator
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            # ----------------------------------
            # shared between containers
            # ----------------------------------
            - name: dpcreator-volume
              mountPath: /dpcreator_volume
              #subPath: 2ravens_org-apricot
              #readOnly: false
          envFrom:
          - configMapRef:
              name: dpcreator-db-data-configmap
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: opendp_project.settings_azure_test_01
            - name: ALLOWED_HOSTS
              value: "{{ ALLOWED_HOSTS }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dpcreator-app-secrets
                  key: secret-key
            - name: CRYPTOGRAPHY_KEY
              valueFrom:
                secretKeyRef:
                  name: dpcreator-app-secrets
                  key: cryptography-key
---
# ---------------------------
# DPCreator - Service
# ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: dpcreator-load-balancer
  labels:
    app: dpcreator
    tier: load-balancer
spec:
  type: LoadBalancer
  # IP mapped to dpcreator.2ravens.org
  loadBalancerIP: {{ loadBalancerIP }}
  selector:
    app: dpcreator
    tier: app
  ports:
  - port: 80
    targetPort: 8000
