name: Cypress Tests

on: [ push ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./client
          run: docker-compose up --build
          wait-on: 'http://0.0.0.0:8000'