name: docker-compose-actions-workflow

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Install dependencies
        run: |
          cd client
          mkdir node_modules
          npm install
      - name: run Cypress tests
        run: |
          cd client
          node_modules/.bin/cypress run
