name: docker-compose-actions-workflow

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./client
          build: npm run build
          start: npm start
