name: docker-compose-actions-workflow

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the client static files
        run: docker-compose-ci-step1.yml
      - name: Build server and test
        run: docker-compose-ci-step2.yml
